temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data = read.csv(unz(temp,"household_power_consumption.txt"), header=TRUE, sep=";", stringsAsFactors=F)
feb = subset(data, as.Date(Date, "%d/%m/%Y") == "2007-02-01" | as.Date(Date, "%d/%m/%Y") == "2007-02-02" )
datetime = paste(feb$Date, feb$Time)
datetime = strptime(datetime, "%d/%m/%Y %H:%M:%S")
feb = cbind(feb, datetime)
png("plot2.png", width = 480, height = 480, units = "px")
plot(x = feb$datetime, y = feb$Global_active_power, type = 'l', xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()