temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data = read.csv(unz(temp,"household_power_consumption.txt"), header=TRUE, sep=";", stringsAsFactors=F)
feb = subset(data, as.Date(Date, "%d/%m/%Y") == "2007-02-01" | as.Date(Date, "%d/%m/%Y") == "2007-02-02" )
datetime = paste(feb$Date, feb$Time)
datetime = strptime(datetime, "%d/%m/%Y %H:%M:%S")
feb = cbind(feb, datetime)
png("plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(x = feb$datetime, y = feb$Global_active_power, type = 'l', xlab = "", ylab = "Global Active Power")
plot(x = feb$datetime, y = feb$Voltage, type = 'l', xlab = "datetime", ylab = "Voltage")
with (feb, plot(datetime, Sub_metering_1, type = 'l', col = 'black', xlab = "", ylab = "Energy sub metering"))
with (feb, points(datetime, Sub_metering_2, type = 'l', col = 'red'))
with (feb, points(datetime, Sub_metering_3, type = 'l', col = 'blue'))
legend("topright", pch=1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(x = feb$datetime, y = feb$Global_reactive_power, type = 'l', xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
